### ISSUE TITLE
Access to `key`on the `customResponder` callback

### ISSUE THREAD

**Issue by acanimal** [cmawhorter/hmmac#13]
Hi,
I'm using hmmac as middleware in my project (https://github.com/acanimal/clyde-hmac-auth) where I'm implementing my custom `customResponder` function.
When authentication is fine, I need to attach information to the `req` object, so I need to have access to the `key` value (line https://github.com/acanimal/clyde-hmac-auth/blob/master/lib/index.js#L47)

Is it possible? Any possibility to pass key information to the `customResponder`?

Cheers.

**Comment by cmawhorter** [comment]
I had the same need and ended up with the following workaround.  I'm thinking credentialProvider needs access to original req object? 

```javascript
app.use(function(req, res, next) {

Hmmac.middleware({ 
    // ...
    credentialProvider: function(key, callback) {
        // ...
        req.username = user.email;
        req.user_id = user.id;

        callback({
            key: user.apikey
          , secret: user.apisecret
        });
    }
  }).apply(this, arguments);

}); // app.use
```

**Comment by acanimal** [comment]
Thanks for the tip.

I think there are two possibilities:

* Pass original `req` to `credentialProvider`.
* Pass the `key` to the `customResponder`.

**Comment by cmawhorter** [comment]
Ah, then you'd want to do `req.user_key = user.apikey`.  That's the http request so it's scoped to just that particular request.  You could attach anything you wanted.  Or you could do res.locals.

**Comment by acanimal** [comment]
I just changed my implementation (see https://github.com/acanimal/clyde-hmac-auth/blob/0737960c953c51b2e2695ddee8c12a5343602de5/lib/index.js#L22) but continues being a workaround :)

I vote for the two previous scenarios.

Cheers.

**Comment by cmawhorter** [comment]
Me too.  Scheduling for 0.3.0.  Will definitely get something added here.

**Comment by cmawhorter** [comment]
These have both been implemented.  It uses `Function.length` to determine whether or not you need the feature:

```js
customResponder(valid, key, req, res, next)
// or 
customResponder(valid, req, res, next)
```

```js
credentialProvider(originalRequest, key, callback) // callback is required even if sync
// or 
credentialProvider(originalRequest [, callback])
```
