### ISSUE TITLE
using hmmac as an express middleware?

### ISSUE THREAD

**Issue by kamikazechaser** [cmawhorter/hmmac#14]
The example is not clear on this plus it says "It doesnt work". Any updated demo for express?

**Comment by cmawhorter** [comment]
sorry about the delay, the issue notification was lost in the noise.  where does it say it doesn't work?  

IIRC, the only problem was that you needed to ensure req.body was available for hmmac to use. 

[there isn't much going on in the middleware](https://github.com/cmawhorter/hmmac/blob/440f2d19090a9e5b21eb02de36fdfe3033a1d50f/lib/hmmac.js#L276), so it should be relatively straightforward to workaround any issues in newer versions of express or other servers.
